#!/bin/sh
# Script to update archlinux system.

echo "pacman -Syu"
sudo pacman -Syu
echo

echo "pkgfile -u"
sudo pkgfile -u
echo

echo "pacman -Scc"
sudo pacman -Scc
echo

echo "updatedb"
sudo updatedb
echo

echo "AUR updates:"
cower -u

echo
echo "Configs to merge:"
locate "*.pacsave"
locate "*.pacnew"
