#!/bin/sh
# Script to update archlinux system.

if [ "$(whoami)" != "root" ]
then
  sudo $0

  echo "AUR updates:"
  cower --update --download --force

  echo
  echo "Configs to merge:"
  locate "*.pacsave"
  locate "*.pacnew"

  exit 0
fi

echo "pacman -Syu"
pacman -Syu
echo

echo "pkgfile -u"
pkgfile -u
echo

echo "pacman -Scc"
pacman -Scc
echo

echo "updatedb"
updatedb
echo
