#!/bin/sh
# Run this like: ./record_screen moviename

# Get this from xrandr or something
resolution=1920x1080

# Change the last two numbers to move the top-left corner of the recording
# rectangle.  i.e. :0.0+600,300 would record offset 600 x, 300 y.  The first
# numbers is for the X display, which is probably always 0.
offset=:0.0+0,0

cmd="ffmpeg \
    -f x11grab \
    -s $resolution \
    -i $offset \
    -c:v libx264 \
    -preset ultrafast \
    -threads 0
    $1.mkv"
echo $cmd
exec $cmd

# IF YOU NEED TO RECORD AUDIO FROM YOUR MICROPHONE, ADD THESE OPTIONS

    #-f alsa \
    #-ac 2 \
    #-acodec flac \
    #-ab 128k \
