#!/bin/sh
# Install slop: https://github.com/naelstrof/slop
#     pacman -S slurp
# Run this like: ./record_screen [-d] [file]
#  -d Include window decorations

if ! which slurp 2>&1 > /dev/null
then
  echo "slurp not installed"
  exit 1
fi

FILTER="\(.rect.x + .window_rect.x),\(.rect.y + .window_rect.y) \(.window_rect.width)x\(.window_rect.height)"

if [ "$1" = "-d" ]
then
  FILTER="\(.rect.x),\(.rect.y - .deco_rect.height) \(.rect.width)x\(.rect.height + .deco_rect.height)"
  shift
fi

# Returns a list of open windows for slurp
get_windows() {
  swaymsg --type get_tree | jq --raw-output "
    [recurse(.nodes[]?) | .nodes] |
    flatten(1) |
    map(select(.type == \"con\" and .visible)) |
    .[] |
    \"$FILTER\""
}

get_windows | slurp | grim -g - $1
