#!/bin/sh

if [ -z "$1" ]
then
    echo "Usage $0 <id>"
    exit 1
fi

ID="$1"
EMULATOR="emu$ID"
HEX=$(python -c "print('{0:02x}'.format($ID))")

export LD_LIBRARY_PATH=/home/tom/programs/android-sdk/tools/lib
sudo ip tuntap add "$EMULATOR" mode tap

sudo -E emulator -avd x86-17-b -qemu -m 512 -enable-kvm -nographic \
    -net nic,vlan=1 -net user,vlan=1,hostname="$EMULATOR" \
    -net nic,vlan=2,macaddr=52:54:00:12:34:$HEX \
    -net tap,ifname=$EMULATOR,script=no,vlan=2

sudo ip tuntap del "$EMULATOR" mode tap
