#!/bin/sh
# swapws - Swaps workspaces in i3.
# Arguments are pairs of workspaces to swap.  Can specify arbitrary number.

wmmsg() {
  case "$XDG_SESSION_TYPE" in
    x11)
      i3-msg $@ > /dev/null
      ;;
    wayland)
      swaymsg $@ > /dev/null
      ;;
  esac
}

swap() {
  wmmsg "rename workspace $1 to tmp"
  wmmsg "rename workspace $2 to $1"
  wmmsg "rename workspace tmp to $2"
}

if [ $# -lt 2 ]
then
  echo "USAGE: $0 <A> <B> [<A> <B> [...]]"
  exit 1
fi

while [ $# -gt 0 ]
do
  swap $1 $2
  shift 2
done
