#!/bin/sh
# swapws - Swaps workspaces in i3.
# Arguments are pairs of workspaces to swap.  Can specify arbitrary number.

swap() {
  i3-msg "rename workspace $1 to tmp" > /dev/null
  i3-msg "rename workspace $2 to $1" > /dev/null
  i3-msg "rename workspace tmp to $2" > /dev/null
}

if [ $# -lt 2 ]
then
  echo "USAGE: $0 <A> <B> [<A> <B> [...]]"
  exit 1
fi

while [ $# -gt 0 ]
do
  swap $1 $2
  shift 2
done
