#!/bin/sh

DRAFT_DIR="$HOME/.drafts"

mkdir -p "$DRAFT_DIR"

DRAFT=$(mktemp --tmpdir="$DRAFT_DIR")

xclip -o -selection clipboard >> "$DRAFT"

vim -c "set ft=mail" -c "set spell" "$DRAFT"

xclip -i -selection clipboard < "$DRAFT"

echo "Delete draft? [y/N]"
read INPUT

if [ "$INPUT" = "y" ]
then
    rm "$DRAFT"
fi
